// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqkpgrfocznbvawihvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcWtwZ3Jmb2N6bmJ2YXdpaHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTA4MTQsImV4cCI6MjA1NTA4NjgxNH0.vg7D0X_mBmS91Vvz7yjOMnbWgt8SsV9m2tM4NdvsvgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);